### ISSUE TITLE
Updating the geometry of an annotation

### ISSUE THREAD

**Issue by TimothySealy** [mapbox/mapbox-annotation-extension#58]
I have some questions regarding the geometry of an annotation:

1. Is the `center` property of the `MGLCircleStyleAnnotation` annotation the same as its geometry? Is seems that when the property is updated, the annotation is displayed on the new location on the map. Also if `center` is the annotations geometry, could it be rename it to `coordinate` for consistency reasons?
2. To my knowledge it is not (always) possible to update the geometry of an annotation in the current implementation. For a circle updating the `center` property seems to work. For a symbol I've used the `updateGeometryCoordinates(withDelta: delta)`. Is this the correct way to update the symbol's geometry? Also is it possible to update the geometry of a `MGLLineStyleAnnotation`?

**Comment by tobrun** [comment]
cc @mapbox/maps-ios

**Comment by captainbarbosa** [comment]
Hey @TimothySealy, thanks for your questions. Hopefully I can provide some clarification:


### `#1`
>Is the center property of the MGLCircleStyleAnnotation annotation the same as its geometry? Is seems that when the property is updated, the annotation is displayed on the new location on the map.

Yes. Under the hood, the center of a `MGLCircleStyleAnnotation` is an [`MGLPointFeature` derived from](https://github.com/mapbox/mapbox-annotation-extension/blob/master/MapboxAnnotationExtension/Annotations/MGLCircleStyleAnnotation.m#L44) our main Maps SDK. The center of a circle style annotation is indeed the same as its geometry.

>Also if center is the annotations geometry, could it be rename it to coordinate for consistency reasons?

That seems reasonable - I've opened https://github.com/mapbox/mapbox-annotation-extension/issues/59 to mark this as a feature request.

### `#2`

>To my knowledge it is not (always) possible to update the geometry of an annotation in the current implementation. For a circle updating the center property seems to work. For a symbol I've used the updateGeometryCoordinates(withDelta: delta). Is this the correct way to update the symbol's geometry? 

`updateGeometryCoordinates(withDelta: delta)` is an internal method we use in this project to support drag/drop operations. It isn't intended to be used publicly (which is why you don't see it in [our API reference](https://docs.mapbox.com/ios/api/annotation-extension/0.0.1-beta.1/Classes/MGLSymbolStyleAnnotation.html)).

>Also is it possible to update the geometry of a MGLLineStyleAnnotation?

Not at this time - you'll need to manually remove/recreate the line style annotation if you want to move it. We know this isn't ideal - this limitation kind of already exists on our current Maps SDK anyways. This is sometime we would like to address directly in our SDK in the future.

Hope this helps answer your questions.

**Comment by tobrun** [comment]
> Not at this time - you'll need to manually remove/recreate the line style annotation if you want to move it. We know this isn't ideal - this limitation kind of already exists on our current Maps SDK anyways. This is something we would like to address directly in our SDK in the future.

We do allow this with the Android equivalent plugin, what is the is issue you are hitting with this @captainbarbosa ?

**Comment by Tapestes** [comment]
@TimothySealy, can you give me some insight on how you used `updateGeometryCoordinates(withDelta: delta)` to move an MGLSymbolStyleAnnotation?  I can't seem to figure out how to access that property.  Thanks much.

**Comment by TimothySealy** [comment]
@Tapestes, you basically compare a Symbol's current position to your new position to compute the delta. Given this delta you can update a Symbol's geometry using `updateGeometryCoordinates(withDelta: delta)`. Please note that this is an internal method which is not intended to be used this way (https://github.com/mapbox/mapbox-annotation-extension/issues/58#issuecomment-560711106).

Have a look at the following code snippet for a working example: https://github.com/tobrun/flutter-mapbox-gl/blob/16439ed8da46576b9af537aa8424d0abf08268e4/ios/Classes/Convert.swift#L236-L243

**Comment by Tapestes** [comment]
Maybe I'm on a different version (I'm using the latest), but when I try to access `updateGeometryCoordinates` I get `Value of type 'MGLSymbolStyleAnnotation' has no member 'updateGeometryCoordinates'`.   Thanks for the code pointer all the same.

**Comment by gabeschine** [comment]
Hello,

I'm also trying to update the coordinates of a line on iOS. It is unfortunate that it is possible on Android but on iOS. I have not yet figured out how to do it. If folks give me pointers I'm happy to implement the feature myself.

Thanks.
